blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security
    url: https://github.com/BryanAlanCouch/skills-introduction-to-github/security
    about: Please report security vulnerabilities here.
